app/server/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(FlaskForm):
    username = StringField('Username', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[
            DataRequired(),
            Length(min=1, max=40)
        ]
    )

    email = StringField(
        'Email Address',
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40)
        ]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

app/server/__init__.py
import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import re


# instantiate the extensions
login_manager = LoginManager()
bcrypt = Bcrypt()
toolbar = DebugToolbarExtension()
db = SQLAlchemy()
migrate = Migrate()



def create_app():

    app = Flask(
        __name__,
        template_folder='../client/templates',
        static_folder='../client/static'
    )

    # set config
    app_settings = os.getenv(
        'APP_SETTINGS', 'app.server.config.DevelopmentConfig')
    app.config.from_object(app_settings)

    # set up extensions
    login_manager.init_app(app)
    bcrypt.init_app(app)
    toolbar.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    # register blueprints
    from app.server.main.views import main_blueprint
    app.register_blueprint(main_blueprint)
    from app.server.user.views import user_blueprint
    app.register_blueprint(user_blueprint)
    from app.server.api.api import api_blueprint
    app.register_blueprint(api_blueprint)


    # flask login
    from app.server.model import User
    login_manager.login_view = 'user.login'
    login_manager.login_message_category = 'danger'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == int(user_id)).first()

    @app.errorhandler(401)
    def unauthorized_page(error):
        return render_template('errors/401.html'), 401

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template('errors/500.html'), 500

    return app

app/server/main/views.py
from flask import render_template, Blueprint, request, flash

main_blueprint = Blueprint('main', __name__,)


@main_blueprint.route('/')
def landing():
    return render_template('main/landing.html')

app/server/user/views.py
import os
from flask import render_template, Blueprint, request, flash, redirect, url_for, jsonify
from app.server.user.forms import LoginForm, RegisterForm
from flask_login import login_user, logout_user, login_required, current_user
from app.server import db, model, bcrypt
import datetime

basedir = os.path.abspath(os.path.dirname(__file__))
user_blueprint = Blueprint('user', __name__,)

@user_blueprint.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = model.User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.landing'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)

    return render_template('user/login.html', form = form)

@user_blueprint.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    return render_template('user/register.html', form = form)

@user_blueprint.route("/register_confirm", methods=['GET', 'POST'])
def register_confirm():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = model.User(
            username = form.username.data,
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash('You are logged in. Welcome!', 'success')
        return redirect(url_for('main.landing'))
    else:
        flash('Incorrect email/password!', 'danger')


@user_blueprint.route("/account/<username>", methods=['GET', 'POST'])
def account(username):
    return render_template('user/account.html')

@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.landing'))

app/client/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Flask-Boilerplate">
  <meta name="author" content="Author">
  <meta name="keywords" content="Flask, Boilerplate, Skeleton">
  <title> Flask-Boilerplate </title>
  <link rel="icon" href="{{url_for('static', filename='images/power-button.png')}}">
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</head>

<body>

  {% include 'header.html' %}

      <div class='container-fluid'>

        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          <br>
          <div class="row">
            <div class="col-md-12">
              {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a> {{message}}
              </div>
              {% endfor %}
            </div>
          </div>
          </br>
          {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}

        </div>

  {% block js %} {% endblock %}
  {% include 'footer.html' %}
</body>

</html>

app/client/templates/footer.html
<footer class="footer">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>


<style>

.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px; /* Set the fixed height of the footer here */
  line-height: 60px; /* Vertically center the text there */
  background-color: #f5f5f5;
}
</style>

app/client/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
      <a class="navbar-brand" href="/">Flask Boilerplate</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/api">API</a>
          </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="/account/{{current_user.username}}">{{current_user.username}}</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="/register">Register</a></li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
</header>

app/client/templates/main/landing.html
{% extends 'base.html' %}

{% block content %}

<div class='row'>
    <h3 style='padding:20px 20px 0px'> Welcome to the Flask Boilerplate </h3>
</div>
<div class='row'>
    <div style='padding:0px 20px'> Get started developing today! </div>
</div>



{% endblock content %}

app/client/templates/user/account.html
{% extends 'base.html' %}

{% block content %}

<div class='row'>
    <h3 style='padding:20px 20px 0px'> Profile Page </h3>
</div>
{% endblock content %}

app/client/templates/user/login.html
{% extends 'base.html' %}

{% block content %}


<div class="container-fluid">
  <div class="row" style='margin:15vh 0px'>
    <div class="col-6 mx-auto my-auto">
      <h4> Log In </h4>
      <form role="form" method="POST" action="/login">
        {{ form.csrf_token }}
        <div> Username </div>
        <div class="input-group form-group">
            {{ form.username(type="text", class="form-control pt-sans-black", placeholder="email")}}
        </div>
        <div> Password </div>
        <div class="input-group form-group">
            {{ form.password(type="password", class="form-control pt-sans-black", placeholder="password")}}
        </div>
        <button class="btn btn-dark" type="submit">Submit</button>
      </form>
      <div style="padding:30px 0px 0px"> Don't have a log in? <a href='/register'> Register Here </a></div>
    </div>
  </div>
</div>

{% endblock content %}

app/client/templates/user/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
  <div class="row" style='margin:10vh 0px'>
    <div class="col-6 mx-auto" >
      <h3> Register </h3>
      <form role="form" name='form' method="POST" action="/register_confirm">
        {{ form.csrf_token }}
        {{ form.hidden_tag()}}
        <div> Username </div>
        <div class="input-group form-group">
            {{ form.username(type="text", class="form-control pt-sans-black", placeholder="username")}}
        </div>
        <div> Email </div>
        <div class="input-group form-group">
            {{ form.email(type="text", class="form-control pt-sans-black", placeholder="email")}}
        </div>
        <div> Password </div>
        <div class="input-group form-group">
            {{ form.password(type="password", input="password", class="form-control pt-sans-black", placeholder="password")}}
        </div>
        <div> Confirm Password </div>
        <div class="input-group form-group">
            {{ form.confirm(type="password", input="password", class="form-control pt-sans-black", placeholder="confirm password")}}
        </div>
        <button class="btn btn-dark" type="button submit">Submit</button>
      </form>
    </div>
  </div>
</div>



{% endblock content %}